### ISSUE TITLE
多切换几次tab，会有一定几率卡住

### ISSUE THREAD

**Issue by jerry12547** [wangchenyan/wan-harmony#3]
设备： 华为p60 
版本号：4.0.0.130
![微信图片_20240319172110](https://github.com/wangchenyan/wan-harmony/assets/13712804/2b3d68ec-0df0-4271-b3e8-2b8de7b5f6c4)
bug：如图

**Comment by wangchenyan** [comment]
再点一下tab能恢复吗

**Comment by jerry12547** [comment]
如果是快速随机点击tab12345切换，不会恢复。但点慢点会有概率恢复

**Comment by wangchenyan** [comment]
你好，api11分支已关闭tab切换动画
